# This is a basic workflow to help you get started with Actions
name: build-ckm-website-frontend

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  OWNER: ${{ github.actor }}
  IMAGE_NAME: ${{github.event.repository.name}}

on:
  push:
    branches:
      - "**"
      - "!development"
      - "!main"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Sets up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn

      - name: Build Angular project
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn

      - name: Yarn lint
        run: yarn lint
